### ISSUE TITLE
Make it easier to setup

### ISSUE THREAD

**Issue by nielsbosma** [tessin/cloud-pad#10] opened 2018-06-12 08:09 UTC
Can we automate the steps where we authenticate and setup the azure function. Also automate the uploading of Linqpad.exe.

**Comment by leidegre** [comment] 2018-06-12 19:59
Right now, the file that makes everything happen is `CloudPad.dll` we could make this an exe file to make it easier to get going quickly.

The problem is that we have to invoke the script that you want to deploy through `LPRun.exe` to be able to run reflection from within the LINQPad script. There's no reason why `CloudPad.exe` itself cannot do this though. It's a little wired because it would mean `CloudPad.exe -> LPRun.exe -> CloudPad.exe` but it should work.

**Comment by leidegre** [comment] 2019-05-29 07:43
Fixed via 2.0 release https://github.com/tessin/cloud-pad/releases/tag/2.0.0

Considerable effort went into streamlining the setup/first run experience of CloudPad 2.0

**Closed as completed by leidegre** 2019-05-29 07:43 UTC
Labels: feature request
